name: sudo-code-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.10
  - bs4
  - openai
  - nltk=3.4
  - google-genai
  - scikit-learn<=1.6.1
  - pip
  - pip:
      - dotenv
      - sapling-py
      - gensim
